version: '3'
services:
  bld-nginx:
    build: ./nginx
    volumes:
      - "./nginx/config/keys:/keys"
    ports:
      - "80:80"
      - "443:443"

  bld-nodejs:
    build: ./nodejs
    expose:
      - 8080
